### ISSUE TITLE
Stream.tscn: creatures don't return to the list if multiples

### ISSUE THREAD

**Issue by plexsoup** [godot-wildlings/Bioenfluencer#7] opened 2019-04-29 07:52 UTC
If you have more than one crafted creature, clicking more than one in the Stream sidebar causes a problem. The creature_on_display should return to the list, but it doesn't.

**Comment by Borupirax** [comment] 2019-04-29 12:57
The function `get_creature_from_storage(index)`  is removing the child according to the matching index from the item clicked in the ItemList.

I tried - 
var creature = creature_storage_container.get_child(index)
var copy_creature = creature.instance()

creature_storage_container.add_child(copy_creature)
creature_storage_container.remove_child(copy_creature)

return creature

I don't know how to make a duplicate of a none-scene node, but the idea is there..

**Comment by Borupirax** [comment] 2019-04-29 16:39
Part of the bug is that selecting multiple creatures will overlay them over one another. I fixed this by removing the creature from the display position each time a creature from ItemList is selected.

I haven't been able yet to fix the main bug.

(This fix was made hours ago. I just forgot to make a comment about it)

**Comment by kvonspiczak** [comment] 2019-05-03 23:33
closing since you cannot create multiple creatures at once anymore

**Closed as completed by kvonspiczak** 2019-05-03 23:33 UTC
